# Generated by Django 4.0.3 on 2022-05-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelordapp', '0003_listing_image1_listing_image2_listing_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='documents',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
